// Mocks generated by Mockito 5.4.5 from annotations
// in bloc_analytics_tracking/test/analytics_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:bloc_analytics_tracking/core/services/analytics_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i2.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void logEvent(String? name, {Map<String, dynamic>? parameters}) =>
      super.noSuchMethod(
        Invocation.method(#logEvent, [name], {#parameters: parameters}),
        returnValueForMissingStub: null,
      );

  @override
  void logLogin({String? method}) => super.noSuchMethod(
    Invocation.method(#logLogin, [], {#method: method}),
    returnValueForMissingStub: null,
  );

  @override
  void logSignUp({String? method}) => super.noSuchMethod(
    Invocation.method(#logSignUp, [], {#method: method}),
    returnValueForMissingStub: null,
  );

  @override
  void logAddToCart({String? itemId, String? itemName, double? price}) =>
      super.noSuchMethod(
        Invocation.method(#logAddToCart, [], {
          #itemId: itemId,
          #itemName: itemName,
          #price: price,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void logPurchase({String? transactionId, double? value, String? currency}) =>
      super.noSuchMethod(
        Invocation.method(#logPurchase, [], {
          #transactionId: transactionId,
          #value: value,
          #currency: currency,
        }),
        returnValueForMissingStub: null,
      );
}
