name: bloc_analytics_tracking
description: "BLoC ile Firebase Analytics entegrasyonu demo projesi"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  # BLoC
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0
  
  # Dependency Injection
  get_it: ^7.6.7
  
  # Routing
  go_router: ^13.2.0
  
  # UI
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.5
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
